import { NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { getSession } from "@/lib/auth";
import { CLASSIFIER_MODEL, inferenceClient } from "@/lib/do-ai";
import { classifyGroup, keywordMatch } from "@/lib/matching";
import { answersToText, type SurveyAnswers } from "@/lib/survey";
import { addMember } from "@/lib/store";
import type { Member } from "@/lib/types";

const DEFAULT_FOLLOWUP = {
  question:
    "Think of a time someone showed up for you when it really mattered. What would it mean to be that person for a neighbor this month?",
  options: [
    "Someone fed me once — I want to pass that on",
    "I know how lonely it gets; nobody should feel invisible",
    "I want my block to feel like it did when I was a kid",
  ],
};

function extractJson<T>(text: string): T | null {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]) as T;
  } catch {
    return null;
  }
}

export async function POST(req: Request) {
  const body = (await req.json()) as { action: "followup" | "complete"; answers: SurveyAnswers };
  const answers = body.answers ?? { causes: [], styles: [], time: "" };
  const client = inferenceClient();

  // One adaptive question, generated by a cheap model from the fixed answers.
  if (body.action === "followup") {
    if (!client) return NextResponse.json({ ...DEFAULT_FOLLOWUP, mode: "mock" });
    try {
      const res = await client.chat.completions.create({
        model: CLASSIFIER_MODEL,
        messages: [
          {
            role: "user",
            content: `A new volunteer answered an onboarding survey: ${answersToText(answers)}
Write ONE intimate, heartfelt follow-up question (max 35 words, no emojis) that clearly references their specific answers and gently asks about the personal "why" underneath — a memory, a person, or a moment that made them care about this. It should feel like a close friend asking, not a form. Also give 3 answer options (max 12 words each, no emojis) written in a vulnerable first-person voice, each hinting at a different kind of story.
Reply with ONLY this JSON: {"question": "...", "options": ["...", "...", "..."]}`,
          },
        ],
        max_completion_tokens: 250,
        temperature: 0.8,
      });
      const parsed = extractJson<{ question: string; options: string[] }>(
        res.choices[0]?.message?.content ?? ""
      );
      if (parsed?.question && Array.isArray(parsed.options)) {
        return NextResponse.json({
          question: parsed.question,
          options: parsed.options.slice(0, 4),
          mode: "inference",
        });
      }
      return NextResponse.json({ ...DEFAULT_FOLLOWUP, mode: "fallback" });
    } catch (err) {
      console.error("survey followup failed:", err);
      return NextResponse.json({ ...DEFAULT_FOLLOWUP, mode: "fallback" });
    }
  }

  // Summarize + classify + create the member profile.
  if (body.action === "complete") {
    const session = await getSession();
    const name = session?.name || "Neighbor";
    const text = answersToText(answers);
    let interests = [...answers.causes, ...answers.styles].slice(0, 6);
    let summary = "";

    if (client) {
      try {
        const res = await client.chat.completions.create({
          model: CLASSIFIER_MODEL,
          messages: [
            {
              role: "user",
              content: `A volunteer named ${name} answered: ${text}
Reply with ONLY this JSON (no emojis anywhere): {"interests": ["3-5 short lowercase interest tags"], "summary": "one warm second-person sentence about how they want to help"}`,
            },
          ],
          max_completion_tokens: 150,
          temperature: 0.5,
        });
        const parsed = extractJson<{ interests: string[]; summary: string }>(
          res.choices[0]?.message?.content ?? ""
        );
        if (parsed?.interests?.length) interests = parsed.interests.slice(0, 6);
        if (parsed?.summary) summary = parsed.summary;
      } catch (err) {
        console.error("survey summary failed:", err);
      }
    }

    const group = client
      ? await classifyGroup(interests, `${summary} ${text}`)
      : keywordMatch(text + " " + interests.join(" "));

    const member: Member = {
      id: randomUUID(),
      name,
      groupId: group.id,
      interests,
      summary,
      joinedAt: new Date().toISOString(),
      userId: session?.id,
      avatarUrl: session?.avatarUrl,
    };
    await addMember(member);
    return NextResponse.json({
      matched: { group, member, interests, summary },
      mode: client ? "inference" : "mock",
    });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
