"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import type { ActionPlan } from "@/lib/types";

const SOURCE_LABEL: Record<ActionPlan["source"], string> = {
  agent: "DigitalOcean agent + knowledge base",
  inference: "DigitalOcean serverless inference",
  mock: "demo mode (no keys configured)",
};

export function PlanSection({
  groupId,
  groupColor,
  initialPlan,
}: {
  groupId: string;
  groupColor: string;
  initialPlan: ActionPlan | null;
}) {
  const [plan, setPlan] = useState<ActionPlan | null>(initialPlan);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate(force: boolean) {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ groupId, force }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Plan generation failed");
      setPlan(data.plan as ActionPlan);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Plan generation failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section>
      <div className="flex flex-wrap items-center gap-3">
        <h2 className="text-xl font-bold">Action plan</h2>
        <button
          onClick={() => generate(Boolean(plan))}
          disabled={busy}
          className="rounded-full px-5 py-2 text-sm font-bold text-white shadow-sm transition disabled:opacity-40"
          style={{ backgroundColor: groupColor }}
        >
          {busy ? "Coordinating…" : plan ? "Regenerate plan" : "Generate this crew's plan"}
        </button>
      </div>

      {error && (
        <div className="mt-4 rounded-xl border-2 border-coral/40 bg-coral/10 px-4 py-3 text-sm">
          {error}
        </div>
      )}

      {!plan && !busy && !error && (
        <p className="mt-4 max-w-md text-sm text-clay">
          The planner agent reads what this crew cares about and what nearby orgs
          need, then drafts the next two weeks.
        </p>
      )}

      {busy && !plan && (
        <p className="mt-4 animate-pulse text-sm text-clay">
          The planner agent is matching your crew with local orgs…
        </p>
      )}

      {plan && (
        <div className="mt-4 rounded-xl bg-white/80 p-5 shadow-sm">
          <div className="plan-md text-[0.95rem]">
            <ReactMarkdown>{plan.markdown}</ReactMarkdown>
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-ink/10 pt-3 text-xs text-clay">
            <span>Generated by {SOURCE_LABEL[plan.source]}</span>
            {plan.citations.length > 0 && (
              <span>
                · sources:{" "}
                {plan.citations.map((c) => (
                  <span key={c} className="mr-1 rounded bg-kraft px-1.5 py-0.5 font-mono">
                    {c}
                  </span>
                ))}
              </span>
            )}
          </div>
        </div>
      )}
    </section>
  );
}
